const MAX_TRANSACTION_AMOUNT = 25000;
const TWO_FACTOR_THRESHOLD = 1000;
const TRANSFER_WINDOW_MS = 15 * 60 * 1000;
const TRANSFER_LIMIT_PER_WINDOW = 5;

module.exports = {
  MAX_TRANSACTION_AMOUNT,
  TWO_FACTOR_THRESHOLD,
  TRANSFER_WINDOW_MS,
  TRANSFER_LIMIT_PER_WINDOW
};
